#DEV environment

app:
  message: This is the propery file for the ${spring.application.name} especific to DEV environment

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=1
    usermane: sa
    password: sa

#debug=true